# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('log_text', models.TextField()),
            ],
        ),
    ]
