# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='log',
            name='log_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
