# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_logger', '0003_auto_20170201_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='log_text',
            new_name='description',
        ),
    ]
