# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_logger', '0005_auto_20170201_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory_logger.Action'),
            preserve_default=False,
        ),
    ]
