# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_logger', '0007_auto_20170201_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='inventory_logger.Action'),
        ),
    ]
