# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
