# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0002_loan_quantity_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='quantity_returned',
            new_name='returned_quantity',
        ),
    ]
