# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20170401_0129'),
        ('inventory_requests', '0003_auto_20170323_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('pdf_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='requestcart',
            name='status',
            field=models.CharField(choices=[('outstanding', 'outstanding'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('denied', 'denied'), ('active', 'active'), ('fulfilled', 'fulfilled'), ('backfill_request_loan', 'backfill_request_loan'), ('backfill_request_outright', 'backfill_request_outright'), ('backfill_transit', 'backfill_transit'), ('backfill_satisfied', 'backfill_satisfied'), ('backfill_failed', 'backfill_failed')], default='active', max_length=40),
        ),
        migrations.AddField(
            model_name='backfill',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_backfills', to='inventory_requests.RequestCart'),
        ),
        migrations.AddField(
            model_name='backfill',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_items', to='items.Item'),
        ),
    ]
