# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0005_auto_20170405_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backfill',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_loan', to='inventory_requests.Loan'),
        ),
        migrations.AlterField(
            model_name='backfill',
            name='status',
            field=models.CharField(choices=[('backfill_request_loan', 'backfill_request_loan'), ('backfill_request_outright', 'backfill_request_outright'), ('backfill_transit', 'backfill_transit'), ('backfill_satisfied', 'backfill_satisfied'), ('backfill_failed', 'backfill_failed')], max_length=40),
        ),
    ]
