# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0006_auto_20170405_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='from_backfill',
            field=models.BooleanField(default=False),
        ),
    ]
