# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0010_auto_20170412_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='backfill',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backfill',
            name='status',
            field=models.CharField(choices=[('backfill_request', 'backfill_request'), ('backfill_transit', 'backfill_transit'), ('backfill_satisfied', 'backfill_satisfied'), ('backfill_failed', 'backfill_failed'), ('backfill_denied', 'backfill_denied'), ('backfill_cancelled', 'backfill_cancelled'), ('backfill_active', 'backfill_active')], default='backfill_active', max_length=40),
        ),
    ]
