# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0011_auto_20170413_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backfill',
            name='file_name',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
