# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0012_auto_20170413_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backfill',
            name='file_name',
            field=models.CharField(default='https://www.youtube.com/watch?v=4p7fB_r77z4', max_length=100),
        ),
    ]
