# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='track_minimum_stock',
            field=models.BooleanField(default=False),
        ),
    ]
