# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0003_auto_20170323_1339'),
        ('items', '0004_auto_20170403_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=40, unique=True)),
                ('disbursement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='inventory_requests.Disbursement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='items.Item')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='inventory_requests.Loan')),
            ],
        ),
    ]
