# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20170214_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('short_text', 'short-form text'), ('long_text', 'long-form text'), ('int', 'integer'), ('float', 'floating-point number')], max_length=16),
        ),
    ]
