# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_item_is_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_asset',
            field=models.BooleanField(default=False),
        ),
    ]
