# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20170409_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='disbursement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory_requests.Disbursement'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory_requests.Loan'),
        ),
    ]
