# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_shopping_cart', '0003_auto_20170217_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
