from enum import Enum


class ActionEnum(Enum):
    REQUEST_DENIED = "REQUEST DENIED"
    REQUEST_APPROVED = "REQUEST APPROVED"
    REQUEST_CANCELLED = "REQUEST CANCELLED"
    REQUEST_CREATED = "REQUEST CREATED"
    REQUEST_MODIFIED = "REQUEST MODIFIED"
    DISBURSED = "DISBURSED"
    ITEM_CREATED = "ITEM CREATED"
    ITEM_DELETED = "ITEM DELETED"
    ITEM_MODIFIED = "ITEM MODIFIED"
    TAG_CREATED = "TAG CREATED"
    TAG_DELETED = "TAG DELETED"
    ADDITIONAL_ITEM_INSTANCES = "ADDITIONAL ITEM INSTANCES"
    DESTRUCTION_ITEM_INSTANCES = "DESTRUCTION ITEM INSTANCES"
    ITEMS_DISBURSED = "ITEMS DISBURSED"
    CUSTOM_FIELD_CREATED = "CUSTOM FIELD CREATED"
    CUSTOM_FIELD_DELETED = "CUSTOM FIELD DELETED"
    CUSTOM_FIELD_VALUE_MODIFIED = "CUSTOM FIELD VALUE MODIFIED"
