from enum import Enum


class ActionEnum(Enum):
    REQUEST_DENIED = "REQUEST DENIED"
    REQUEST_APPROVED = "REQUEST APPROVED"
    REQUEST_CANCELLED = "REQUEST CANCELLED"
    REQUEST_CREATED = "REQUEST CREATED"
    REQUEST_MODIFIED = "REQUEST MODIFIED"
    DISBURSED = "DISBURSED"
    ITEM_CREATED = "ITEM CREATED"
    ITEM_DELETED = "ITEM DELETED"
    ITEM_MODIFIED = "ITEM MODIFIED"
    TAG_CREATED = "TAG CREATED"
    TAG_DELETED = "TAG_DELETED"
    ADDITIONAL_ITEM_INSTANCES = "ADDITIONAL_ITEM_INSTANCES"
    DESTRUCTION_ITEM_INSTANCES = "DESTRUCTION_ITEM_INSTANCES"
    ITEM_ADDED_TO_CART = "ITEM_ADDED_TO_CART"
    ITEM_DELETED_FROM_CART = "ITEM_DELETED_FROM_CART"
    REQUESTED_QUANTITY_MODIFIED = "REQUESTED_QUANTITY_MODIFIED"
    ITEMS_DISBURSED = "ITEMS_DISBURSED"
    CUSTOM_FIELD_CREATED = "CUSTOM_FIELD_CREATED"
