# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 03:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_email', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedManagers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_managers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.RemoveField(
            model_name='itemlog',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemlog',
            name='log',
        ),
        migrations.RemoveField(
            model_name='log',
            name='affected_user',
        ),
        migrations.RemoveField(
            model_name='log',
            name='initiating_user',
        ),
        migrations.RemoveField(
            model_name='log',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='requestcartlog',
            name='log',
        ),
        migrations.RemoveField(
            model_name='requestcartlog',
            name='request_cart',
        ),
        migrations.DeleteModel(
            name='ItemLog',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='RequestCartLog',
        ),
    ]
