# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_email', '0002_auto_20170320_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_tag', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
