# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_transaction_logger', '0002_auto_20170223_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='effected_user',
            new_name='affected_user',
        ),
    ]
