# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_transaction_logger', '0003_auto_20170223_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlog',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_log', to='inventory_transaction_logger.Log'),
        ),
    ]
