# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_shopping_cart', '0003_auto_20170217_0112'),
        ('inventory_transaction_logger', '0004_auto_20170223_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='inventory_shopping_cart.ShoppingCart')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_log', to='inventory_transaction_logger.Log')),
            ],
        ),
    ]
