# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_disbursements', '0007_auto_20170219_1727'),
        ('inventory_transaction_logger', '0006_auto_20170224_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementCartLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_cart', to='inventory_disbursements.Cart')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_log', to='inventory_transaction_logger.Log')),
            ],
        ),
    ]
