# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0002_auto_20170309_1601'),
        ('inventory_transaction_logger', '0007_disbursementcartlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCartLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_log', to='inventory_transaction_logger.Log')),
                ('request_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='inventory_requests.RequestCart')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingcartlog',
            name='log',
        ),
        migrations.RemoveField(
            model_name='shoppingcartlog',
            name='shopping_cart',
        ),
        migrations.DeleteModel(
            name='ShoppingCartLog',
        ),
    ]
