# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_shopping_cart', '0004_auto_20170226_2056'),
        ('inventory_transaction_logger', '0008_auto_20170311_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_log', to='inventory_transaction_logger.Log')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='inventory_shopping_cart.ShoppingCart')),
            ],
        ),
        migrations.AlterField(
            model_name='requestcartlog',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_cart_log', to='inventory_transaction_logger.Log'),
        ),
        migrations.AlterField(
            model_name='requestcartlog',
            name='request_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_cart', to='inventory_requests.RequestCart'),
        ),
    ]
