# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_disbursements', '0002_disbursement_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed', to='items.Item'),
        ),
    ]
