# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_disbursements', '0003_auto_20170211_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('disburser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disburser', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='disburser',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='inventory_disbursements.Cart'),
        ),
    ]
