# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_disbursements', '0004_auto_20170219_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
