# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_disbursements', '0005_auto_20170219_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='inventory_disbursements.Cart'),
        ),
    ]
