# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_disbursements', '0006_auto_20170219_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
