# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_disbursements', '0007_auto_20170219_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursed', to='items.Item'),
        ),
    ]
