# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20170216_2337'),
        ('inventory_disbursements', '0008_auto_20170226_2309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disbursement',
            unique_together=set([('cart', 'item')]),
        ),
    ]
