from enum import Enum


class ActionEnum(Enum):
    REQUEST_DENIED = "REQUEST DENIED"
    REQUEST_APPROVED = "REQUEST APPROVED"
    REQUEST_CANCELLED = "REQUEST CANCELLED"
    REQUEST_CREATED = "REQUEST CREATED"
    REQUEST_MODIFIED = "REQUEST MODIFIED"
    DISBURSED = "DISBURSED"
    ITEM_CREATED = "ITEM CREATED"
    ITEM_DESTROYED = "ITEM DESTROYED"
    ITEM_MODIFIED = "ITEM MODIFIED"
