# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_tag', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedManagers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_managers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
