# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0004_auto_20160607_0901'),
        ('inventory_email_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanReminderEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_reminder_emails', to='post_office.Email')),
            ],
        ),
    ]
