# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_email_support', '0002_loanreminderemails'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanReminderSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('executed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='loanreminderemails',
            name='email',
        ),
        migrations.DeleteModel(
            name='LoanReminderEmails',
        ),
    ]
