# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_email_support', '0003_auto_20170323_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrependedBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepended_body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
