# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_shopping_cart_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttable',
            old_name='quantity',
            new_name='quantity_requested',
        ),
    ]
