# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_shopping_cart_request', '0005_auto_20170226_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttable',
            name='quantity',
        ),
    ]
