# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_shopping_cart_request', '0006_remove_requesttable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttable',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
