# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_shopping_cart_request', '0007_requesttable_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
